ignore surface finishing errors when generating PNGs
with PNGs writing the output file has already happened at this point,
unlike with the other formats where this is handled as part of the
finish() method

recently calls to finish() started to sometimes fail with

cairo.Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)

even though the PNG output had already successfully been written.

So we are now ignoring any exceptions thrown by finish() if the output
format is PNG